before_install: sudo apt-get install libicu-dev libmagic-dev -y
language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies
# install:
#  - "pip install charlockholmes"
branches:
  only:
    - master
# command to run tests
script:
  - "cd test"
  - "python test.py"
