before_install: sudo apt-get install libicu-dev libmagic-dev -y
language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - master
# command to run tests
script:
  - "python setup.py install"
  - "cd test"
  - "python test.py"
